# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark stale issues and pull requests

on:
  issues:
    types: ['opened', 'reopened']

permissions:
  issues: write

jobs:
  close:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.1
    - run: gh issue close ${{ github.event.issue.number }}
